// Dados simulados de vendas
const data = [
    { codigo: "QXTD", nome: "anabeltrandicas10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "T5WZ", nome: "elaine10", vendas: "30", comissao: "R$: 647,97", bonus: "R$: 190", comissao_total:"R$: 837,97", ranking: "7" }, 
    { codigo: "AVE7", nome: "dicasdaclarinha10", vendas: "25", comissao: "R$: 539,98", bonus: "R$: 190", comissao_total:"R$: 729,98", ranking: "9" }, 
    { codigo: "VBQ4", nome: "majestade10", vendas: "2", comissao: "R$: 43,2", bonus: "R$: 0", comissao_total:"R$: 43,2", ranking: "27" }, 
    { codigo: "SSW8", nome: "CHRISMENEZES10", vendas: "108", comissao: "R$: 2347,19", bonus: "R$: 540", comissao_total:"R$: 2887,19", ranking: "2" }, 
    { codigo: "3ERF", nome: "alivia10", vendas: "37", comissao: "R$: 820,53", bonus: "R$: 190", comissao_total:"R$: 1010,53", ranking: "5" }, 
    { codigo: "OD96", nome: "miihmourao10", vendas: "16", comissao: "R$: 345,58", bonus: "R$: 70", comissao_total:"R$: 415,58", ranking: "11" }, 
    { codigo: "1576", nome: "peace10", vendas: "1", comissao: "R$: 26,1", bonus: "R$: 0", comissao_total:"R$: 26,1", ranking: "32" }, 
    { codigo: "AS61", nome: "manoelarosa10", vendas: "45", comissao: "R$: 971,96", bonus: "R$: 190", comissao_total:"R$: 1161,96", ranking: "4" }, 
    { codigo: "ROXJ", nome: "diariobelezaemfoco10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "HT7F", nome: "JUHVITAMINA10", vendas: "1", comissao: "R$: 21,6", bonus: "R$: 0", comissao_total:"R$: 21,6", ranking: "32" }, 
    { codigo: "TUH4", nome: "juh10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "81J2", nome: "achadinhosssgabi10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "UIL2", nome: "beautyrayy10", vendas: "3", comissao: "R$: 64,8", bonus: "R$: 0", comissao_total:"R$: 64,8", ranking: "24" }, 
    { codigo: "EU3Z", nome: "obatempromo10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "HLSC", nome: "quebarato10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "ICT8", nome: "priirubio10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "LOCH", nome: "deboracarlos10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "L21O", nome: "marjoreserena10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "DRJI", nome: "achadinhos10", vendas: "2", comissao: "R$: 43,2", bonus: "R$: 0", comissao_total:"R$: 43,2", ranking: "27" }, 
    { codigo: "FCFQ", nome: "aninhaskin", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "PI7C", nome: "promosualinda10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "I274", nome: "achadosdanessa10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "OQT9", nome: "adoramospromocao10", vendas: "10", comissao: "R$: 215,99", bonus: "R$: 70", comissao_total:"R$: 285,99", ranking: "14" }, 
    { codigo: "62FP", nome: "suellem10", vendas: "5", comissao: "R$: 108", bonus: "R$: 20", comissao_total:"R$: 128", ranking: "21" }, 
    { codigo: "4VDN", nome: "isis10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "6YVH", nome: "LARAAKEL10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "ASU4", nome: "QUALAPROMODEHOJE10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "EY6Z", nome: "ANA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "FSVS", nome: "PRISCILAROLLO10", vendas: "20", comissao: "R$: 453,58", bonus: "R$: 190", comissao_total:"R$: 643,58", ranking: "10" }, 
    { codigo: "W1DT", nome: "PROMOLOUCAS10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "3R4A", nome: "DICABARATEZA10", vendas: "2", comissao: "R$: 43,2", bonus: "R$: 0", comissao_total:"R$: 43,2", ranking: "27" }, 
    { codigo: "DQLM", nome: "OQUEELAAMA10", vendas: "7", comissao: "R$: 151,2", bonus: "R$: 20", comissao_total:"R$: 171,2", ranking: "18" }, 
    { codigo: "BXDC", nome: "DICASDAPATHY10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "QH6I", nome: "DICASDEBELEZADAGAH10", vendas: "8", comissao: "R$: 172,8", bonus: "R$: 20", comissao_total:"R$: 192,8", ranking: "17" }, 
    { codigo: "NKRO", nome: "BRUNABEAUTY10", vendas: "1", comissao: "R$: 21,6", bonus: "R$: 0", comissao_total:"R$: 21,6", ranking: "32" }, 
    { codigo: "6C39", nome: "MELANDRADE10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "SM4U", nome: "DIADEBELEZA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "VMZE", nome: "DICASDATAMI10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "FAMX", nome: "MARCELAPAIVA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "22XR", nome: "DICASENTREDICAS10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "Q4Z1", nome: "SABRINAPAIM10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "74T5", nome: "TAYSAVILA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "MVJA", nome: "ESTHERGOMES10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "34Y7", nome: "MILENAMARTIL10", vendas: "49", comissao: "R$: 1069,2", bonus: "R$: 190", comissao_total:"R$: 1259,2", ranking: "3" }, 
    { codigo: "9NHS", nome: "ANADAMASCENO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "6R45", nome: "ROTINADEUMAPELE10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "UEK9", nome: "RESANTANA10", vendas: "4", comissao: "R$: 86,4", bonus: "R$: 0", comissao_total:"R$: 86,4", ranking: "23" }, 
    { codigo: "X9KE", nome: "ACHADOSDEPRECINHOS10", vendas: "1", comissao: "R$: 21,6", bonus: "R$: 0", comissao_total:"R$: 21,6", ranking: "32" }, 
    { codigo: "7BU7", nome: "BIALOU10", vendas: "12", comissao: "R$: 259,2", bonus: "R$: 70", comissao_total:"R$: 329,2", ranking: "13" }, 
    { codigo: "LL54", nome: "DICASDANESSA10", vendas: "396", comissao: "R$: 8567,69", bonus: "R$: 540", comissao_total:"R$: 9107,69", ranking: "1" }, 
    { codigo: "HG44", nome: "BLOGDABELEZA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "E5ZJ", nome: "LUIZACORTI10", vendas: "3", comissao: "R$: 64,8", bonus: "R$: 0", comissao_total:"R$: 64,8", ranking: "24" }, 
    { codigo: "VEJG", nome: "ESSANOSSAPELE10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "UCX7", nome: "BELEZACOMGIO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "V4C8", nome: "COISASDATAY10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "JHDE", nome: "BLOGDICAJU10", vendas: "1", comissao: "R$: 21,6", bonus: "R$: 0", comissao_total:"R$: 21,6", ranking: "32" }, 
    { codigo: "FEL1", nome: "DICASBYDEIA10", vendas: "9", comissao: "R$: 194,4", bonus: "R$: 20", comissao_total:"R$: 214,4", ranking: "16" }, 
    { codigo: "XC5T", nome: "METADEAR10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "ZW2O", nome: "BLOOGUERICES10", vendas: "1", comissao: "R$: 21,6", bonus: "R$: 0", comissao_total:"R$: 21,6", ranking: "32" }, 
    { codigo: "KFCB", nome: "RICHELEMELO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "GGHB", nome: "LARISSAOLY10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "ZG8N", nome: "DUDACARVALHO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "JWUE", nome: "NATHBARROS10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "ED58", nome: "LELESILVA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "CNBP", nome: "EMYLOHANA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "HL8B", nome: "JULIADEOLINDO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "8J78", nome: "RITUALSKINCAREARI10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "XA6P", nome: "MARIAHMARTINEZ10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "1X5G", nome: "OHLIVIAMARIA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "TKIZ", nome: "MAISDEBELEZA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "Z1JU", nome: "VALERIARODRIGUES10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "MAQS", nome: "GAROTAPODEROSA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "NJ5J", nome: "MELHORACHADINHOONLINE10", vendas: "3", comissao: "R$: 64,8", bonus: "R$: 0", comissao_total:"R$: 64,8", ranking: "24" }, 
    { codigo: "3LDV", nome: "EVOLUIDAPELE10", vendas: "35", comissao: "R$: 756", bonus: "R$: 190", comissao_total:"R$: 946", ranking: "6" }, 
    { codigo: "H5OX", nome: "JESSICANATALIA10", vendas: "7", comissao: "R$: 151,2", bonus: "R$: 20", comissao_total:"R$: 171,2", ranking: "18" }, 
    { codigo: "3W4Z", nome: "TIPSBYMAI10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "BW6M", nome: "DICASDAHAI10", vendas: "1", comissao: "R$: 21,6", bonus: "R$: 0", comissao_total:"R$: 21,6", ranking: "32" }, 
    { codigo: "DFLW", nome: "CUIDADOSDAISA10", vendas: "10", comissao: "R$: 216", bonus: "R$: 70", comissao_total:"R$: 286", ranking: "14" }, 
    { codigo: "KQ67", nome: "PRISCILALIROW10", vendas: "13", comissao: "R$: 280,8", bonus: "R$: 70", comissao_total:"R$: 350,8", ranking: "12" }, 
    { codigo: "M1V3", nome: "JULIALANDIM10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "34CR", nome: "THAIZAOLIVEIRA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "DAGE", nome: "THATS10", vendas: "27", comissao: "R$: 583,2", bonus: "R$: 190", comissao_total:"R$: 773,2", ranking: "8" }, 
    { codigo: "HC8W", nome: "BYLUANASANTOS10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "X6Z1", nome: "ACHADINHOSDAINDY10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "17EX", nome: "BIAGIFFONI10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "EJ12", nome: "DUDAMDAILY10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "8LXB", nome: "LULINDAILY10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "8Y7O", nome: "GABICAMARGO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "OUZ4", nome: "TAIZELIMA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "L4BE", nome: "TANARAFP10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "OWI7", nome: "KETH10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "JRH2", nome: "VINNI10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "9BHQ", nome: "BIANCAIZALBERTI10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "NHBR", nome: "INDY10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "K98K", nome: "SOFI10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "SM2H", nome: "SUBLI10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "THB3", nome: "NATHMOURA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "HK6R", nome: "BEAUTIESANDMAKES10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "INQ8", nome: "HANNAKATIELI10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "T3GP", nome: "LELEDOGMA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "C8HI", nome: "ACHADOSDALILIGARCIA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "DK47", nome: "NICOLERILOS10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "UBLN", nome: "MARIAZEVEDO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "8AI1", nome: "BIFAO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "85DF", nome: "MANUVAGUEIRO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "5JHL", nome: "DRIMARTINS10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "MFBO", nome: "RAFABORIN10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "SS4A", nome: "BEMINA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "TEYV", nome: "MANU10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "W91G", nome: "NATIGUITLER10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "5TUD", nome: "JOALVES10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "BR7X", nome: "FADABRANQUINHO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "257K", nome: "RHAMI10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "1H25", nome: "DICASDEPELES10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "PWNL", nome: "DUDADAIER10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "3LUE", nome: "JOSIELYSOUSA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "USIH", nome: "JUSCYNAIRA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "KC68", nome: "THUANYPLAZZI10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "SXTO", nome: "NANI10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "O7TR", nome: "CAROLA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "QHXK", nome: "NATHSELEPRIM10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "NVN5", nome: "BRUNOALVES10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "EIZT", nome: "MARCELA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "YTGW", nome: "LEIDIFELICIO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "EZB1", nome: "LARISOARES10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "UL3L", nome: "INAEBEATRIZ10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "ZE6S", nome: "LIVIAMOLETI10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "BFHV", nome: "APOLO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "XFL2", nome: "CAMILLACOSTA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "2FPI", nome: "LARISSACOZER10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "OUPJ", nome: "ALEDIORIO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "DTD1", nome: "BIAMARTINEZ10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "1RTE", nome: "MIILENAMISS10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "MK13", nome: "KAIQUEALMEIDA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "RTEC", nome: "BRUNACARVALHO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "O5AA", nome: "DAFNEMELO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "DRA3", nome: "DEYSEANACLETO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "TPGU", nome: "ALEXANDRE10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "GYD3", nome: "SARAHDORNELLES10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "55WW", nome: "ALANA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "A5NQ", nome: "GIOVIEIRA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "81LV", nome: "LAURINHA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "DZYO", nome: "CAROLGAMA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "YF99", nome: "MARIARAUJO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "X6K9", nome: "DRINACCARATO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "IQ2V", nome: "LILIVELOSO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "TYG5", nome: "GABIRIBEIRO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "ME3S", nome: "MANUCIT10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "VSYK", nome: "ISABINOW10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "M4SK", nome: "LESOARES10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "KCT3", nome: "HOLANDEUSO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "A65A", nome: "JULLIACASTRO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "S7FK", nome: "FLAVIANUNES10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "FB6Z", nome: "DICANANET10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "ET1G", nome: "NATACHASOUSA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "IXT2", nome: "LIARAHORIE10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "D516", nome: "JULIAFACO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "4W44", nome: "CAMILAMORENA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "UKCU", nome: "FABIANALANO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "CMY9", nome: "MARYALMEIDA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "CO6R", nome: "SABRINAMELO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "V287", nome: "CUIDADOSDACAMI10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "8QQ3", nome: "RAFAELASANTOS10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "FVV9", nome: "SKINCAREDEHOJE10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "O5KC", nome: "CAROLMONTEIRO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "JK6X", nome: "DICASDALINI10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "PXXM", nome: "NOSSAPELEIMPERFEITA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "1I3B", nome: "RAFATEIXEIRA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "9MAM", nome: "SARAHMONACO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "YGAV", nome: "GABRIELAFERNANDA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "8WDN", nome: "STARSPINK10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "OB81", nome: "GARIMPONLINE10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "YP1F", nome: "VICRUZS10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "GHTR", nome: "VAHTORQUATOBEAUTY10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "AUQ7", nome: "MACEDAILYY10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "NKZ9", nome: "MALUMEDINA10", vendas: "2", comissao: "R$: 43,2", bonus: "R$: 0", comissao_total:"R$: 43,2", ranking: "27" }, 
    { codigo: "FPJX", nome: "NUTRIMILAALMEIDA10", vendas: "5", comissao: "R$: 108", bonus: "R$: 20", comissao_total:"R$: 128", ranking: "21" }, 
    { codigo: "LRZU", nome: "BRENDOLETA10", vendas: "1", comissao: "R$: 21,6", bonus: "R$: 0", comissao_total:"R$: 21,6", ranking: "32" }, 
    { codigo: "6OS6", nome: "DICASCOMABRU10", vendas: "2", comissao: "R$: 43,2", bonus: "R$: 0", comissao_total:"R$: 43,2", ranking: "27" }, 
    { codigo: "VMVN", nome: "THAISSIMOESADV10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "75IQ", nome: "JOYCECUSTODIO10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "P1BK", nome: "RAFAELAULLA10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "UEYY", nome: "BRUNOCASTILHO10", vendas: "7", comissao: "R$: 151,2", bonus: "R$: 20", comissao_total:"R$: 171,2", ranking: "18" }, 
    { codigo: "118X", nome: "ISABELAFERRER10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "LOCP", nome: "SNAKEPROMOS10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "IA49", nome: "CAMILASANTOS10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 
    { codigo: "TRFZ", nome: "ALINEFUNGACS10", vendas: "0", comissao: "R$: 0", bonus: "R$: 0", comissao_total:"R$: 0", ranking: "40" }, 

     
 
    // Adicione os dados restantes da sua planilha
];

// Elementos do DOM
const codigoInput = document.getElementById("codigoInput");
const buscarButton = document.getElementById("buscarButton");
const resultadoDiv = document.getElementById("resultado");

// Event listener para o botão de busca
buscarButton.addEventListener("click", () => {
    const codigo = codigoInput.value;
    // Procurando o produto pelo código
    const produto = data.find(item => item.codigo === codigo);

    if (produto) {
        // Exibindo os detalhes do produto se encontrado
        resultadoDiv.innerHTML = `
            <p><strong>Nome:</strong> ${produto.nome}</p>
            <p><strong>Vendas:</strong> ${produto.vendas}</p>
            <p><strong>Comissão (sem bônus):</strong> ${produto.comissao}</p>
            <p><strong>Bônus:</strong> ${produto.bonus}</p>
            <p><strong>Comissão Total:</strong> ${produto.comissao_total:}</p>
            <p><strong>Ranking mensal:</strong> ${produto.ranking}</p>
        `;
    } else {
        // Exibindo mensagem se o produto não for encontrado
        resultadoDiv.innerHTML = "<p>Código não encontrado.</p>";
    }
});


